# Generated by Django 2.0.2 on 2018-03-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='has_read',
            field=models.BooleanField(default=True, verbose_name='是否已读'),
        ),
    ]
