# Generated by Django 2.0.2 on 2018-03-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180320_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='has_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
    ]
